name: build

on: [pull_request]

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - uses: actions/setup-node@v1
        with: { node-version: 14.x }
      - uses: actions/cache@v2
        with:
          path: |
            node_modules
            */*/node_modules
          key: ${{ runner.os }}-${{ hashFiles('**/yarn.lock') }}
      - name: Build and Verify
        run: |
          yarn install --frozen-lockfile
          yarn verify
      - uses: actions/upload-artifact@v2
        with:
          name: build-artifact
          path: dist
